let products = {
    vases: [
        {
            id: 1,
            series: "Sozia Wine Bottle",
            currency: "$",
            price: 105,
            imgUrl: "4.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 2,
            series: "Neutral Ceramic Vase",
            currency: "$",
            price: 85,
            imgUrl: "3.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 3,
            series: "Twist",
            currency: "$",
            price: 125,
            imgUrl: "2.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 4,
            series: "Rayne Abstract Vase",
            currency: "$",
            price: 115,
            imgUrl: "1.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ],
    lamps: [
        {
            id: 5,
            series: "Sofia Lamp",
            currency: "$",
            price: 105,
            imgUrl: "4.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 6,
            series: "Neutral Ceramic Lamp",
            currency: "$",
            price: 85,
            imgUrl: "3.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 7,
            series: "Twist Lamp",
            currency: "$",
            price: 125,
            imgUrl: "2.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 8,
            series: "Rayne Abstract Lamp",
            currency: "$",
            price: 115,
            imgUrl: "1.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ],
    glasses: [
        {
            id: 9,
            series: "Sofia Glass",
            currency: "$",
            price: 105,
            imgUrl: "5.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 10,
            series: "Neutral Ceramic Glass",
            currency: "$",
            price: 85,
            imgUrl: "6.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 11,
            series: "Twist Glass",
            currency: "$",
            price: 125,
            imgUrl: "7.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 12,
            series: "Rayne Abstract Glass",
            currency: "$",
            price: 115,
            imgUrl: "8.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ],
    accessories: [
        {
            id: 13,
            series: "Sofia Accessory",
            currency: "$",
            price: 105,
            imgUrl: "9.jpg",
            description: "Over the years, the timeless Sozia vase has become a genuine classic. Most people associate the vase with minimalis and functional design. Right now you are looking at the 15 cm coloured porcelain vases. The Sozia vase is available in a wide range of colours and sizes.",
            designer: "Sozia Porcelean",
            sku: 200775,
            colour: "multicolor",
            material: "porcelean",
            height: 15,
            unit: "cm"
        },
        {
            id: 14,
            series: "Neutral Ceramic Accessory",
            currency: "$",
            price: 85,
            imgUrl: "10.jpg",
            description: "Bring peace, serenity, and balance to your space with Sage & Sill's Shades of Neutral Ceramic Vases. Made of stunning matte ceramic, these vases feature six unique designs that make a statement by themselves or in a group. Perfect for dried flowers, grasses, or florals, these vases are sure to elevate your decor and leave you feeling zen!",
            designer: "Sageandsill",
            sku: 206575,
            colour: "rose",
            material: "ceramic",
            height: 18,
            unit: "cm"
        },
        {
            id: 15,
            series: "Twist Accessory",
            currency: "$",
            price: 125,
            imgUrl: "11.jpg",
            description: "Sight Unseen references Renaissance paintings and historic French ceramics in this collection of pastel-toned and nude porcelain plates and vases",
            designer: "Sight Unseen",
            sku: 312775,
            colour: "nude",
            material: "ceramic",
            height: 20,
            unit: "cm"
        },
        {
            id: 16,
            series: "Rayne Abstract Accessory",
            currency: "$",
            price: 115,
            imgUrl: "12.jpg",
            description: "The crisp lines and sharp angles of these striking ceramic vases bring a sense of artful sophistication to a tabletop, shelf, or mantel. Display flowers or use them as a focal point in your decor, these vases are compliment worthy.",
            designer: "Letifly",
            sku: 222775,
            colour: "black",
            material: "ceramic",
            height: 15,
            unit: "cm"
        }
    ]
}